version: '3'

services:
  db:
    image: mysql:8.0.20
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - api-example
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./app/:/var/www/app/
    networks:
      - api-example
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./app/:/var/www/app/
    ports:
      - 8000:80
    networks:
      - api-example

volumes:
  db_app:

networks:
  api-example:
    driver: bridge